#!/usr/bin/env python3
"""Part 3: STM32(10)+ESP32(6)+进阶(8)+iOS(6)+项目(6)+场景(3)+练习(3)+面试(2)"""
from _gen_part1 import rich, ch, tbl, cd, ALL
import _gen_part2  # noqa: F401 — populates ALL

STM32 = [
('01-入门.html','STM32 01：入门','STM32入门','STM32 家族 F/G/H/L/U，为何工业标准，开发板选择。',
 [('1. 家族',tbl(['系列','定位'],[['F1/F4','通用主流'],['H7','高性能'],['L0/L4','超低功耗'],['U5','安全+低功耗']])),
  ('2. 为何学', '<p>求职嵌入式最常见；外设丰富；CubeMX 生态；从 F103 到 H7 路线清晰。</p>'),
  ('3. 开发板',tbl(['板','特点'],[['Blue Pill F103','12元便宜'],['Nucleo','带ST-Link'],['Discovery','带屏传感器']])),
  ('4. 首个工程',cd('c','int main(void){\n  HAL_Init(); SystemClock_Config(); MX_GPIO_Init();\n  while(1){ HAL_GPIO_TogglePin(GPIOC,GPIO_PIN_13); HAL_Delay(500);}\n}'))],
 '求职嵌入式 STM32 是必修课。',None,
 [('F103 过时?','入门够用，工业仍大量在用。'),('Mac?','CubeIDE 有 macOS 版。'),('vs ESP32?','STM32 控，ESP32 连。')],
 ['ST工业标准','F103入门H7高性能','Nucleo带ST-Link','HAL+CubeMX'],'02-CubeMX入门.html','02-CubeMX'),
('02-CubeMX入门.html','STM32 02：CubeMX 入门','CubeMX','图形化配时钟/GPIO/UART，生成工程。',
 [('1. 流程','<ol><li>选芯片/NUCLEO</li><li>Pinout 点引脚</li><li>Clock 配 PLL</li><li>Project→Generate</li></ol>'),
  ('2. 引脚配置',tbl(['模式','用途'],[['GPIO_Output','LED'],['GPIO_EXTI','按键'],['USART1','串口'],['I2C1','传感器']])),
  ('3. 生成目录',cd('text','Core/Src/main.c — 用户代码区 USER CODE BEGIN/END\nDrivers/ — HAL 库\n.ioc — 可重新打开 CubeMX')),
  ('4. 规则', '<p>只在 USER CODE 区写逻辑，避免 regenerate 覆盖。</p>')],
 '改 .ioc 重新 Generate，别手改 generated 文件。',None,
 [('覆盖代码?','写 USER CODE 区内。'),('时钟红叉?','PLL 倍频超规格。'),('HAL vs LL?','HAL 易用 LL 高效。')],
 ['CubeMX 配引脚时钟','Generate 生成 HAL','USER CODE 区写逻辑','.ioc 可版本管理'],'03-时钟树配置.html','03-时钟'),
('03-时钟树配置.html','STM32 03：时钟树配置','时钟树','HSE/HSI、PLL 倍频、APB 分频、SystemCoreClock。',
 [('1. 时钟源',tbl(['源','频率','用途'],[['HSE','8MHz 晶振','精确'],['HSI','8MHz RC','备用'],['PLL','倍频','系统主频']])),
  ('2. 72MHz 示例',cd('text','HSE 8MHz → PLL ×9 → SYSCLK 72MHz\nAHB /1 → 72MHz\nAPB1 /2 → 36MHz (定时器×2=72)\nAPB2 /1 → 72MHz')),
  ('3. 影响', '<p>SystemCoreClock 错 → HAL_Delay/波特率/SysTick 全错。UART 波特率=PCLK/(16×USARTDIV)。</p>'),
  ('4. 验证',cd('c','printf("SYSCLK=%lu\\n", HAL_RCC_GetSysClockFreq());'))],
 'Delay 不对先查时钟树。',None,
 [('HSI vs HSE?','HSE 精度高，HSI 免晶振。'),('APB 定时器?','分频≠1时定时器时钟×2。'),('低功耗?','降频+关外设时钟。')],
 ['时钟决定一切延时','PLL 倍频到目标','APB 分频影响定时器','printf 验证频率'],'04-GPIO与HAL.html','04-GPIO'),
('04-GPIO与HAL.html','STM32 04：GPIO 与 HAL','GPIO HAL','推挽/开漏/上拉/速度，HAL_GPIO 读写。',
 [('1. HAL API',cd('c','HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET);\nGPIO_PinState s = HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13);\nHAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);')),
  ('2. 初始化结构',cd('c','GPIO_InitTypeDef g={0};\ng.Pin=GPIO_PIN_13; g.Mode=GPIO_MODE_OUTPUT_PP;\ng.Pull=GPIO_NOPULL; g.Speed=GPIO_SPEED_FREQ_LOW;\nHAL_GPIO_Init(GPIOC, &g);')),
  ('3. 模式',tbl(['模式','场景'],[['OUTPUT_PP','LED'],['INPUT_PULLUP','按键'],['OUTPUT_OD','I2C'],['AF_PP','UART/SPI']])),
  ('4. BSRR 寄存器', '<p>HAL 底层写 BSRR 原子置位/复位，避免读-改-写竞态。</p>')], 
 'AF 模式由 CubeMX 配，别手动改除非懂 remap。',None,
 [('读 WritePin?','用 ReadPin。'),('速度 LOW/HIGH?','高速边沿陡，可能 EMI。'),('JTAG 占脚?','Disable SWD 释放。')],
 ['HAL_GPIO 三件套','PP/OD/AF 模式','BSRR 原子操作','CubeMX 生成 Init'],'05-UART驱动.html','05-UART'),
('05-UART驱动.html','STM32 05：UART 驱动','UART','HAL_UART_Transmit/Receive，printf 重定向，DMA。',
 [('1. 阻塞发送',cd('c','uint8_t msg[]="Hello\\r\\n";\nHAL_UART_Transmit(&huart1, msg, sizeof(msg)-1, 100);')),
  ('2. printf 重定向',cd('c','int _write(int fd, char *ptr, int len){\n  HAL_UART_Transmit(&huart1,(uint8_t*)ptr,len,HAL_MAX_DELAY);\n  return len;\n}')),
  ('3. 中断接收',cd('c','HAL_UART_Receive_IT(&huart1, &rx_byte, 1);\nvoid HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart){\n  // 处理 rx_byte; 再启动 Receive_IT\n}')),
  ('4. 波特率', '<p>115200 8N1；PCLK 变化需重算 USARTDIV。</p>')], 
 'RX 中断里别阻塞，快速入队。',None,
 [('printf 无输出?','检查 _write 链接。'),('乱码?','时钟/波特率。'),('DMA?','大缓冲高效收发。')],
 ['HAL_UART 阻塞/中断/DMA','_write 重定向 printf','RxCpltCallback 链式接收','115200 8N1'],'06-SPI驱动.html','06-SPI'),
('06-SPI驱动.html','STM32 06：SPI 驱动','SPI','HAL_SPI_TransmitReceive，W25Q Flash 读 ID。',
 [('1. 全双工',cd('c','uint8_t tx[2]={0x9F,0xFF}, rx[2]={0};\nHAL_SPI_TransmitReceive(&hspi1, tx, rx, 2, 100);\n// rx[1] 可能是 Flash 制造商 ID')),
  ('2. CS 控制',cd('c','HAL_GPIO_WritePin(GPIOA, CS_Pin, GPIO_PIN_RESET);\nHAL_SPI_Transmit(&hspi1, cmd, len, 100);\nHAL_GPIO_WritePin(GPIOA, CS_Pin, GPIO_PIN_SET);')),
  ('3. 模式', '<p>CubeMX 选 Mode0-3 对应 CPOL/CPHA，与 Flash 手册一致。</p>'),
  ('4. 速率', '<p>分频器调 SCK；PCB 长线降速加匹配。</p>')], 
 'SPI 模式不对读到 0xFF/0x00。',None,
 [('只发不收?','Transmit 或 TX 填 0xFF。'),('DMA SPI?','大数据块用。'),('3线?','半双工 MISO/MOSI 共用。')],
 ['TransmitReceive 全双工','软件控 CS','模式查 slave 手册','降速排查波形'],'07-I2C驱动.html','07-I2C'),
('07-I2C驱动.html','STM32 07：I2C 驱动','I2C','HAL_I2C_Mem_Read/Write，OLED/EEPROM。',
 [('1. 写寄存器',cd('c','HAL_I2C_Mem_Write(&hi2c1, 0x3C<<1, 0x00, I2C_MEMADD_SIZE_8BIT, &cmd, 1, 100);')),
  ('2. 读传感器',cd('c','uint8_t reg=0xF7; uint8_t buf[6];\nHAL_I2C_Mem_Write(&hi2c1, BME_ADDR, reg, 1, &reg, 1, 100);\nHAL_I2C_Mem_Read(&hi2c1, BME_ADDR, reg, 1, buf, 6, 100);')),
  ('3. 扫描', '<p>HAL_I2C_IsDeviceReady(&hi2c1, addr<<1, 3, 10) 试地址。</p>'),
  ('4. 错误',tbl(['现象','原因'],[['HAL_BUSY','总线死锁，重新 Init'],['NACK','地址/上拉/供电']]))],
 'I2C 死锁可 clock 9 脉冲或 reinit。',None,
 [('7位地址?','HAL 左移1位+R/W。'),('400kHz?','Fast Mode 加上拉。'),('SMBus?','I2C 子集带超时。')],
 ['Mem_Read/Write 带寄存器地址','IsDeviceReady 扫描','NACK查地址上拉','400k 需强上拉'],'08-ADC与DMA.html','08-ADC'),
('08-ADC与DMA.html','STM32 08：ADC 与 DMA','ADC DMA','多通道扫描+DMA 环缓冲，音频/波形采集。',
 [('1. 配置', '<p>ADC1 多通道 scan + DMA circular mode → 缓冲区自动更新。</p>'),
  ('2. 启动',cd('c','HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adc_buf, ADC_BUF_LEN);\n// 半满/全满回调处理数据')),
  ('3. 电压换算',cd('c','float v = adc_buf[i] * 3.3f / 4095.0f;')),
  ('4. vs 轮询',tbl(['方式','CPU','场景'],[['Poll','阻塞','单次读'],['DMA','几乎零占用','连续采样']]))],
 'DMA 缓冲用 volatile 或 cache invalidate (H7)。',None,
 [('采样率?','ADC clock+采样周期。'),('参考电压?','VDDA 或 VREFINT 校准。'),('双ADC?','同步采样。')],
 ['Scan+DMA 连续采集','Circular 环缓冲','半满回调处理','省 CPU 做滤波'],'09-定时器与PWM.html','09-PWM'),
('09-定时器与PWM.html','STM32 09：定时器与 PWM','定时器PWM','TIM PWM 模式，频率占空比，舵机/电机。',
 [('1. PWM 公式',cd('text','freq = TIM_CLK / ((PSC+1)*(ARR+1))\nduty = (CCR+1)/(ARR+1)')),
  ('2. 启动',cd('c','HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);\n__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, 750); // 75% duty')),
  ('3. 舵机 50Hz', '<p>ARR 定 20ms 周期，CCR 1-2ms 脉宽。</p>'),
  ('4. 输入捕获', '<p>测外部脉冲宽度，超声波/编码器。</p>')], 
 '高级定时器 TIM1/8 可驱动电机互补 PWM+死区。',None,
 [('PSC ARR?','预分频与自动重装。'),('互补输出?','H桥电机。'),('编码器模式?','TIM 硬件解码。')],
 ['PSC/ARR 定频率','CCR 定占空比','50Hz 舵机标准','输入捕获测脉宽'],'10-看门狗.html','10-看门狗'),
('10-看门狗.html','STM32 10：看门狗','看门狗','IWDG/WWDG，喂狗策略，防死机。',
 [('1. 独立 IWDG', '<p>LSI 驱动，一旦启动无法停止，超时复位。适合防程序跑飞。</p>'),
  ('2. 窗口 WWDG', '<p>必须在窗口内喂狗，太早太晚都复位。</p>'),
  ('3. 喂狗',cd('c','HAL_IWDG_Init(&hiwdg);\nwhile(1){ /* 主循环 */ HAL_IWDG_Refresh(&hiwdg); }')),
  ('4. 策略', '<p>只在「健康路径」喂狗；卡死在中断/死循环则复位恢复。</p>')], 
 '调试时可暂时不启 IWDG，量产必须开。',None,
 [('喂狗间隔?','看超时配置。'),('RTOS?','Idle hook 或专用任务喂。'),('复位原因?','RCC flag 读 IWDG reset。')],
 ['IWDG 独立看门狗','主循环健康才喂','RTOS 专用任务喂','读 flag 知复位原因'],'../ESP32/01-入门与STM32对比.html','ESP32 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in STM32:
    ALL.append(ch(f'STM32/{f}',t,'STM32 专题','STM32',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

ESP = [
('01-入门与STM32对比.html','ESP32 01：入门与 STM32 对比','ESP32入门','双核 Wi-Fi/BT，Arduino vs IDF，与 STM32 分工。',
 [('1. 架构',tbl(['组件','说明'],[['PRO CPU','协议栈/Wi-Fi'],['APP CPU','用户代码'],['NVS','配置存储'],['RTC','Deep Sleep']])),
  ('2. vs STM32',tbl(['','ESP32','STM32'],[['联网','内置Wi-Fi/BLE','需外接模块'],['实时','较弱','强'],['生态','Arduino/IDF','CubeMX/HAL'],['场景','IoT 原型','工业控制']])),
  ('3. 框架', '<p>原型 Arduino 快；量产 ESP-IDF（FreeRTOS 原生、低功耗全）。</p>'),
  ('4. 分工', '<p>典型产品：STM32 控电机传感器 + ESP32 负责联网 —— 或单 ESP32 全包。</p>')],
 'IoT+iOS 优先 ESP32；工业实时选 STM32。',None,
 [('Arduino vs IDF?','快 vs 全。'),('双核?','Wi-Fi 占一核，用户另一核。'),('GPIO 少?','扩展 I2C GPIO 芯片。')],
 ['ESP32 联网强','双核 Wi-Fi/BT','Arduino 原型 IDF 量产','与 STM32 可分工'],'02-WiFi-STA与AP.html','02-WiFi'),
('02-WiFi-STA与AP.html','ESP32 02：WiFi STA 与 AP','WiFi STA AP','连路由、开热点、SmartConfig 配网思路。',
 [('1. STA',cd('c','WiFi.mode(WIFI_STA);\nWiFi.begin(ssid, pass);\nwhile(WiFi.status()!=WL_CONNECTED) delay(500);')),
  ('2. AP 配网',cd('c','WiFi.softAP("ESP32-Setup", "12345678");\n// WebServer 收 ssid/pass 后切 STA')),
  ('3. SmartConfig', '<p>ESP-Touch / AirKiss 手机发 UDP 编码 SSID —— 类似声波配网。</p>'),
  ('4. 重连',cd('c','if(WiFi.status()!=WL_CONNECTED){ WiFi.disconnect(); WiFi.begin(ssid,pass);}'))],
 '配网 UX 决定产品第一印象，iOS 开发者优势区。',None,
 [('Captive Portal?','连 AP 弹网页配网。'),('WiFiMulti?','保存多组凭据。'),('mDNS?','esp32.local 发现。')],
 ['STA 连路由','AP 热点配网','SmartConfig 免输入','断线自动重连'],'03-BLE-GATT.html','03-BLE'),
('03-BLE-GATT.html','ESP32 03：BLE GATT','BLE GATT','NimBLE/Bluedroid，Service/Characteristic，Notify iOS。',
 [('1. 初始化',cd('c','BLEDevice::init("SmartLamp");\nBLEServer *s = BLEDevice::createServer();\nBLEService *svc = s->createService(LAMP_SERVICE_UUID);')),
  ('2. Characteristic',cd('c','BLECharacteristic *c = svc->createCharacteristic(POWER_UUID,\n  BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_WRITE | BLECharacteristic::PROPERTY_NOTIFY);\nc->setCallbacks(new LampCallbacks()); svc->start();')),
  ('3. 广播',cd('c','BLEAdvertising *adv = BLEDevice::getAdvertising();\nadv->addServiceUUID(LAMP_SERVICE_UUID); adv->start();')),
  ('4. iOS 对接', '<p>固定 UUID 写入 App；Notify 推状态；Write 控开关。</p>')], 
 'NimBLE 比 Bluedroid 省 RAM，IDF 5 推荐。',None,
 [('连不上?','广播/UUID/权限。'),('MTU?','517 减开销。'),('多连接?','参数 max connections。')],
 ['GATT Service/Char','Notify 推状态','Write 收命令','UUID 与 iOS 一致'],'04-Deep-Sleep.html','04-Sleep'),
('04-Deep-Sleep.html','ESP32 04：Deep Sleep','Deep Sleep','Light/Deep Sleep，µA 级，RTC 唤醒。',
 [('1. 模式',tbl(['模式','功耗','唤醒'],[['Active','~100mA','—'],['Modem Sleep','~20mA','Wi-Fi 保连接'],['Deep Sleep','~10µA','GPIO/Timer/RTC']])),
  ('2. Deep Sleep',cd('c','esp_sleep_enable_timer_wakeup(60 * 1000000ULL); // 60s\nesp_deep_sleep_start();')),
  ('3. 数据保持',cd('c','RTC_DATA_ATTR int boot_count = 0; // RTC 内存保留\nboot_count++;')),
  ('4. 设计', '<p>传感器节点：睡 59 分钟醒 1 分钟上报 MQTT。</p>')], 
 'Deep Sleep 掉电 RAM，仅 RTC 内存保留。',None,
 [('Light vs Deep?','Light 保 RAM 耗 mA。'),('GPIO 唤醒?','ext0/ext1。'),('Wi-Fi 睡?','Modem sleep 保连接。')],
 ['Deep Sleep µA 级','RTC_DATA_ATTR 保留','定时/GPIO 唤醒','IoT 电池必备'],'05-NVS存储.html','05-NVS'),
('05-NVS存储.html','ESP32 05：NVS 存储','NVS','键值对、Wear leveling、加密分区。',
 [('1. IDF NVS',cd('c','nvs_handle_t h; nvs_open("storage", NVS_READWRITE, &h);\nnvs_set_i32(h, "boot", ++count); nvs_commit(h); nvs_close(h);')),
  ('2. Arduino Preferences', '<p>封装 NVS，API 类似 UserDefaults。</p>'),
  ('3. 分区',cd('text','nvs分区在 partition table; 可 nvs_flash_erase 恢复出厂')),
  ('4. 加密', '<p>NVS 加密需 flash 加密 + nvs_flash_secure_init。</p>')], 
 '键名长度有限，namespace 规划好。',None,
 [('满?','nvs_flash_erase 或换分区。'),('字符串?','nvs_set_str/get_str。'),('Blob?','nvs_set_blob 存结构体。')],
 ['NVS=键值存储','Wear leveling','Preferences 封装','分区表规划'],'06-HTTP与WebServer.html','06-HTTP'),
('06-HTTP与WebServer.html','ESP32 06：HTTP 与 WebServer','HTTP WebServer','AsyncWebServer 配网页、REST API、与 URLSession 对接。',
 [('1. WebServer',cd('c','AsyncWebServer server(80);\nserver.on("/api/status", HTTP_GET, [](AsyncWebServerRequest *r){\n  r->send(200, "application/json", "{\\"temp\\":25.3}");\n});\nserver.begin();')),
  ('2. 配网页', '<p>PROGMEM HTML 表单 POST /save → 写 NVS → 重启 STA。</p>'),
  ('3. iOS URLSession',cd('swift','let url = URL(string: "http://192.168.4.1/api/status")!\nURLSession.shared.dataTask(with: url) { data,_,_ in /* parse JSON */ }.resume()')),
  ('4. HTTPS', '<p>设备端 TLS 证书管理复杂；内网可用 HTTP，公网必须 TLS。</p>')], 
 'AP 模式下 192.168.4.1 是常见配网地址。',None,
 [('Async vs sync?','Async 不阻塞。'),('CORS?','App WebView 可能需。'),('OTA HTTP?','/update POST 固件。')],
 ['WebServer 配网+API','JSON REST','iOS URLSession 对接','量产考虑 TLS'],'../进阶/01-FreeRTOS任务.html','进阶 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in ESP:
    ALL.append(ch(f'ESP32/{f}',t,'ESP32 专题','ESP32',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

ADV = [
('01-FreeRTOS任务.html','进阶 01：FreeRTOS 任务','FreeRTOS任务','Task 创建、优先级、vTaskDelay、对照 GCD。',
 [('1. 创建',cd('c','xTaskCreate(sensor_task, "sensor", 4096, NULL, 5, NULL);\nxTaskCreate(wifi_task, "wifi", 8192, NULL, 4, NULL);\nvTaskStartScheduler();')),
  ('2. 对照',tbl(['FreeRTOS','iOS'],[['Task','DispatchQueue'],['vTaskDelay','Task.sleep'],['Priority','QoS']])),
  ('3. 栈大小', '<p>uxTaskGetStackHighWaterMark 监测剩余栈，防溢出。</p>'),
  ('4. 结构', '<p>sensor 读数据 → Queue → wifi 发 MQTT，解耦阻塞。</p>')], 
 '栈给够，监测 HighWaterMark。',None,
 [('栈溢出?','增大或优化局部数组。'),('vTaskDelay(0)?','yield 同优先级。'),('idle hook?','喂狗/低功耗。')],
 ['xTaskCreate 参数','优先级数字大优先','vTaskDelay 非阻塞等待','监测栈水位'],'02-同步机制.html','02-同步'),
('02-同步机制.html','进阶 02：同步机制','同步机制','Queue/Semaphore/Mutex/EventGroup。',
 [('1. Queue',cd('c','QueueHandle_t q = xQueueCreate(10, sizeof(SensorData));\nxQueueSend(q, &data, portMAX_DELAY);\nxQueueReceive(q, &data, portMAX_DELAY);')),
  ('2. Mutex',cd('c','SemaphoreHandle_t m = xSemaphoreCreateMutex();\nxSemaphoreTake(m, portMAX_DELAY); /* 访问 SPI */ xSemaphoreGive(m);')),
  ('3. EventGroup', '<p>多位事件同步，如 Wi-Fi 连上 AND 传感器就绪。</p>'),
  ('4. 对照',tbl(['RTOS','Swift'],[['Queue','AsyncStream/Channel'],['Mutex','NSLock'],['Semaphore','DispatchSemaphore']]))], 
 '共享 SPI/I2C 总线必须 Mutex。',None,
 [('ISR 用 Queue?','xQueueSendFromISR。'),('优先级反转?','Mutex 继承。'),('死锁?','固定加锁顺序。')],
 ['Queue 传数据','Mutex 保临界区','EventGroup 多条件','FromISR 专用 API'],'03-低功耗设计.html','03-低功耗'),
('03-低功耗设计.html','进阶 03：低功耗设计','低功耗','Sleep/Stop/Standby，外设关钟，Tickless。',
 [('1. 层次',tbl(['层级','MCU','ESP32'],[['跑满','mA','~100mA'],['Sleep','µA~mA','Deep Sleep µA'],['关电','0','0']])),
  ('2. STM32 Stop', '<p>停 PLL，GPIO 保持，中断唤醒，µA 级。</p>'),
  ('3. Tickless', '<p>FreeRTOS configUSE_TICKLESS_IDLE，空闲进低功耗。</p>'),
  ('4. 测量', '<p>万用表串 ammeter 测 uA；Power Profiler Kit 更准。</p>')], 
 'Wi-Fi 是功耗大户，上报完睡 Deep Sleep。',None,
 [('GPIO 唤醒?','EXTI/RTC。'),('RAM 丢?','Stop 保留 Standby 丢。'),('BLE 连接?','Connection interval 调大。')],
 ['分层降功耗','关无用外设时钟','Tickless Idle','测 uA 验证'],'04-OTA固件升级.html','04-OTA'),
('04-OTA固件升级.html','进阶 04：OTA 固件升级','OTA','双分区、HTTPS OTA、版本号、回滚。',
 [('1. 分区',cd('text','factory | ota_0 | ota_1 | nvs\n运行 ota_0 下载到 ota_1 切换')),
  ('2. ESP32',cd('c','httpUpdate.update(client, "https://server/fw.bin");')),
  ('3. 安全', '<p>HTTPS + 签名校验；防中间人刷恶意固件。</p>'),
  ('4. App 触发', '<p>MQTT cmd=update → 设备拉固件 → 重启 → 上报新版本。</p>')], 
 'OTA 失败保留旧分区可回滚。',None,
 [('Brick?','双分区+回滚。'),('进度?','HTTPClient 回调。'),('差分?','esp_delta_ota 省流量。')],
 ['双分区 A/B','HTTPS+签名','版本号管理','MQTT 触发更新'],'05-Bootloader.html','05-Bootloader'),
('05-Bootloader.html','进阶 05：Bootloader','Bootloader','启动加载、IAP、UART/USB DFU。',
 [('1. 流程', '<p>上电 → Bootloader 检查标志 → 进 App 或升级模式。</p>'),
  ('2. IAP', '<p>In-Application Programming，App 内写 Flash 升级自身。</p>'),
  ('3. STM32', '<p>BOOT0 引脚 + 串口 USART1 ISP；或 USB DFU。</p>'),
  ('4. 版本',cd('c','#define FW_VERSION "1.2.3"\nconst char *ver __attribute__((section(".version")));'))], 
 'Bootloader 区保护，App 不可擦。',None,
 [('变砖?','UART 恢复 ISP。'),('签名?','ECDSA 验签。'),('AB 切换?','otadata 分区指针。')],
 ['Bootloader 独立区','IAP/OTA 入口','BOOT0 串口恢复','版本段独立'],'06-内存优化.html','06-内存'),
('06-内存优化.html','进阶 06：内存优化','内存优化','栈/堆/静态分配，内存池，避免碎片。',
 [('1. 原则', '<ul><li>大缓冲放静态/全局</li><li>避免频繁 malloc/free</li><li>字符串用固定 char[]</li></ul>'),
  ('2. 池化',cd('c','static uint8_t pool[4096];\n// 简易 allocator 或 FreeRTOS heap_4')),
  ('3. 工具', '<p>map 文件看 .bss/.data；heap_caps_get_free_size(ESP32)。</p>'),
  ('4. 对照', '<p>无 ARC；泄漏 = 堆只减不增直到复位。</p>')], 
 'KB 级 RAM 要精打细算。',None,
 [('栈 vs 堆?','任务栈预分配；堆动态。'),('heap_1-5?','heap_4 常用带合并。'),('PSRAM?','ESP32 扩展注意 DMA。')],
 ['静态优于动态','内存池减碎片','map 文件分析','监测 heap 剩余'],'07-JTAG与SWD调试.html','07-调试'),
('07-JTAG与SWD调试.html','进阶 07：JTAG 与 SWD 调试','JTAG SWD','ST-Link/J-Link 断点、单步、Watch 变量。',
 [('1. SWD 线',cd('text','SWDIO / SWCLK / GND / 3.3V — 4线调试')),
  ('2. CubeIDE', '<p>Debug As → STM32 C/C++ Application → 断点 F5 继续 F6 单步。</p>'),
  ('3. OpenOCD',cd('bash','openocd -f interface/stlink.cfg -f target/stm32f1x.cfg')),
  ('4. vs 串口',tbl(['','printf','SWD'],[['侵入性','低','需 halt'],['看变量','字符串','任意'],['硬故障','难查','精准']]))], 
 'HardFault 用 LR/PC 查 CFSR 寄存器。',None,
 [('J-Link vs ST-Link?','J-Link 快支持广。'),('ESP32 JTAG?','内置，需 USB 桥。'),('RTT?','SEGGER 无串口 log。')],
 ['SWD 四线调试','断点单步看变量','OpenOCD/GDB','HardFault 必备'],'08-代码规范.html','08-规范'),
('08-代码规范.html','进阶 08：代码规范','代码规范','MISRA 要点、模块分层 BSP/HAL/App、Git 协作。',
 [('1. 分层',cd('text','App/ — 业务逻辑\nBoard/ — 板级驱动\nMiddleware/ — RTOS/MQTT\nDrivers/ — HAL/CMSIS')),
  ('2. 命名', '<p>模块前缀 led_init；宏 LED_PIN；避免 magic number。</p>'),
  ('3. 头文件', '<p>#pragma once；最小 include；extern "C" 供 C++ 调。</p>'),
  ('4. Git', '<p>.ioc 进版本库；generated 可忽略或 CI 再生；语义化版本 tag。</p>')], 
 '规范代码 six month 后的自己感谢。',None,
 [('MISRA 全遵守?','车规才严格，IoT 抓重点。'),('匈牙利?','type 前缀可选。'),('单元测?','Unity/CMock 测纯逻辑。')],
 ['App/BSP/HAL 分层','一致命名','头文件最小依赖','Git+CI 自动化'],'../iOS联动/01-BLE基础.html','iOS 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in ADV:
    ALL.append(ch(f'进阶/{f}',t,'进阶','进阶',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

IOS = [
('01-BLE基础.html','iOS 联动 01：BLE 基础','BLE基础','GAP/GATT 回顾，Central/Peripheral，与 MCU 分工。',
 [('1. 架构',cd('text','ESP32 Peripheral 广播 → iPhone Central 扫描连接 → GATT 读写')),
  ('2. 权限',cd('xml','<key>NSBluetoothAlwaysUsageDescription</key>\n<string>用于连接智能灯</string>')),
  ('3. 状态机', '<p>poweredOn → scan → connect → discoverServices → discoverCharacteristics → subscribe notify。</p>'),
  ('4. 分工', '<p>MCU 实现 GATT Server；iOS 做 Client UI —— 你熟悉的一侧。</p>')], 
 '真机调试，模拟器无 BLE。',None,
 [('扫不到?','UUID/名称/权限/广播间隔。'),('后台?','bluetooth-central background mode。'),('Android?','权限模型不同。')],
 ['Central/Peripheral 角色','Info.plist 权限','GATT 发现流程','MCU 做 Peripheral'],'02-CoreBluetooth实战.html','02-CB实战'),
('02-CoreBluetooth实战.html','iOS 联动 02：CoreBluetooth 实战','CoreBluetooth','CBManager/CBPeripheral，读写 Notify 完整 Swift 代码。',
 [('1. Central',cd('swift','class BLEManager: NSObject, CBCentralManagerDelegate {\n  var central: CBCentralManager!\n  override init() { central = CBCentralManager(delegate: self, queue: .main) }\n  func centralManagerDidUpdateState(_ c: CBCentralManager) {\n    if c.state == .poweredOn { c.scanForPeripherals(withServices: [svcUUID]) }\n  }\n}')),
  ('2. 连接读写',cd('swift','func peripheral(_ p: CBPeripheral, didDiscoverCharacteristicsFor s: CBService, error: Error?) {\n  for ch in s.characteristics ?? [] {\n    if ch.properties.contains(.notify) { p.setNotifyValue(true, for: ch) }\n  }\n}\nfunc peripheral(_ p: CBPeripheral, didUpdateValueFor ch: CBCharacteristic, error: Error?) {\n  print(ch.value as Any)\n}')),
  ('3. 写控制',cd('swift','peripheral.writeValue(Data([0x01]), for: powerChar, type: .withResponse)')),
  ('4. MVVM', '<p>LampViewModel 持有 BLEManager，@Published 驱动 SwiftUI。</p>')], 
 'Retain peripheral 引用，别被 ARC 释放。',None,
 [('didDisconnect?','自动 reconnect 策略。'),('withResponse?','可靠写，慢；without 快。'),('MTU?','maximumWriteValueLength。')],
 ['CBCentralManager 状态机','discover+notify','writeValue 控制','MVVM 绑定 UI'],'03-WiFi配网.html','03-配网'),
('03-WiFi配网.html','iOS 联动 03：WiFi 配网','WiFi配网','Captive Portal、SmartConfig、BLE 传凭据。',
 [('1. Captive Portal', '<p>连 ESP AP → 自动弹 WebView 填 SSID/密码 → POST 保存。</p>'),
  ('2. BLE 配网',cd('swift','// 写 Wi-Fi 凭据 Characteristic\nlet payload = ssid.data(using:.utf8)! + pass.data(using:.utf8)!\nperipheral.writeValue(payload, for: wifiProvChar, type: .withResponse)')),
  ('3. iOS 14+ 本地网',cd('xml','<key>NSLocalNetworkUsageDescription</key>\n<string>发现局域网设备</string>')),
  ('4. UX', '<ol><li>引导开蓝牙</li><li>扫描设备</li><li>选 Wi-Fi（NEHotspotConfiguration 可选）</li><li>成功反馈</li></ol>')], 
 '配网失败率产品最大吐槽点之一。',None,
 [('Hotspot Config?','NEHotspotConfiguration 帮连 Wi-Fi。'),('ESP-Touch?','乐鑫 SmartConfig App。'),('企业 Wi-Fi?','802.1X 复杂。')],
 ['Captive Portal 常见','BLE 传凭据','本地网络权限','UX 引导关键'],'04-MQTT-App端.html','04-MQTT App'),
('04-MQTT-App端.html','iOS 联动 04：MQTT App 端','MQTT App','CocoaMQTT 订阅主题，远程控灯，JSON  payload。',
 [('1. 连接',cd('swift','import CocoaMQTT\nlet mqtt = CocoaMQTT(clientID: "ios-\\(UUID().uuidString)", host: "broker.emqx.io", port: 1883)\nmqtt.connect()')),
  ('2. 订阅发布',cd('swift','mqtt.subscribe("home/lamp/+/status")\nmqtt.publish(CocoaMQTTMessage(topic: "home/lamp/1/cmd", string: "ON"))')),
  ('3. 架构',cd('text','ESP32 pub sensor → Broker → iOS sub 显示\niOS pub cmd → Broker → ESP32 sub 执行')),
  ('4. TLS', '<p>8883 端口 + 证书 pinning 生产必备。</p>')], 
 'clientID 唯一，clean session 看场景。',None,
 [('QoS?','1 常用。'),(' retained?','上线收最后状态。'),('WebSocket MQTT?','8884/ws 穿防火墙。')],
 ['CocoaMQTT 连接','pub/sub 主题','JSON 协议约定','TLS 生产必须'],'05-全栈架构.html','05-全栈'),
('05-全栈架构.html','iOS 联动 05：全栈架构','全栈架构','MCU+App+云+OTA 架构图，模块边界，协议设计。',
 [('1. 四层',cd('text','Device(Firmware) → Connectivity(BLE/MQTT) → Cloud(Broker/API) → App(SwiftUI)')),
  ('2. 协议',tbl(['通道','协议','数据'],[['近场','BLE GATT','实时控灯'],['远程','MQTT','状态/sync'],['配网','HTTP/BLE','凭据'],['升级','HTTPS OTA','固件.bin']])),
  ('3. 模块', '<p>固件：BSP/HAL/App/Middleware；App：BLE/MQTT/Repository/UI。</p>'),
  ('4. 版本', '<p>语义化 semver；App 检查设备 fw 版本提示升级。</p>')], 
 '协议文档化，固件 App 各一份 JSON schema。',None,
 [('自建云?','MQTT+REST 够 MVP。'),('HomeKit?','MFi 门槛。'),('多设备?','device_id 主题隔离。')],
 ['四层架构清晰','协议文档化','模块边界','版本协同 OTA'],'06-后台蓝牙.html','06-后台'),
('06-后台蓝牙.html','iOS 联动 06：后台蓝牙','后台蓝牙','bluetooth-central 模式，State Restoration，连接保持。',
 [('1. Background Modes',cd('xml','<key>UIBackgroundModes</key>\n<array><string>bluetooth-central</string></array>')),
  ('2. Restoration',cd('swift','central = CBCentralManager(delegate: self, queue: .main,\n  options: [CBCentralManagerOptionRestoreIdentifierKey: "com.app.ble"])')),
  ('3. 限制', '<p>iOS 后台 BLE 可维持连接收 Notify，但扫描受限；勿期望无限后台算力。</p>'),
  ('4. 策略', '<p>关键事件 Notify 唤醒 App；非实时用 MQTT push。</p>')], 
 '后台 BLE 耗电，产品需权衡。',None,
 [('willRestoreState?','恢复 peripheral 列表。'),('被杀?','State restoration 重建。'),('Android 后台?','策略更松。')],
 ['bluetooth-central 模式','State Restoration','Notify 唤醒','远程用 MQTT+Push'],'../项目实战/01-智能台灯.html','项目 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in IOS:
    ALL.append(ch(f'iOS联动/{f}',t,'iOS 联动','iOS联动',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

PROJ = [
('01-智能台灯.html','项目实战 01：智能台灯','智能台灯','PWM 调光+BLE+App+可选 MQTT，完整 MVP。',
 [('1. 功能',tbl(['功能','实现'],[['调光','LEDC PWM'],['开关','BLE Write'],['场景','App 预设'],['远程','MQTT optional']])),
  ('2. 硬件',cd('text','ESP32 + MOSFET/PWM 驱动 LED 灯带 + 5V 电源')),
  ('3. 里程碑','<ol><li>PWM 调光验证</li><li>BLE GATT</li><li>SwiftUI App</li><li>演示视频</li></ol>'),
  ('4. 简历', '<p>「独立实现 ESP32 固件 + iOS CoreBluetooth 智能灯控，支持 0-100% 无级调光」</p>')], 
 'GitHub + 1 分钟 demo 视频。',None,
 [('周期?','3-5天 MVP。'),('成本?','<80元。'),('安全?','低压 LED 无 220V。')],
 ['PWM+BLE+App','MVP 里程碑','作品集素材','低压安全'],'02-远程开关.html','02-开关'),
('02-远程开关.html','项目实战 02：远程开关','远程开关','继电器+MQTT+App，云端控制家电（合规模块）。',
 [('1. 功能','<p>App/MQTT 发 ON/OFF → ESP32 GPIO → 继电器 → 负载。</p>'),
  ('2. 状态回传',cd('text','publish home/switch/1/status ON\nsubscribe home/switch/1/cmd')),
  ('3. 安全', '<p>220V 用现成合规模块；原型用 5V 风扇/demo 灯。</p>'),
  ('4. OTA', '<p>加入 HTTP OTA 字段升级能力。</p>')], 
 '强电务必合规，副业不接无 CE/3C 风险的量产强电。','220V 必须合规范模块。',
 [('反馈?','读继电器辅助触点/电流传感器。'),('掉电记忆?','NVS 存最后状态。'),('本地按钮?','GPIO 中断双控。')],
 ['MQTT 远程控','状态回传','强电合规','NVS 记忆'],'03-环境监测.html','03-环境'),
('03-环境监测.html','项目实战 03：环境监测','环境监测','温湿度+光照+MQTT+App 图表。',
 [('1. 传感器', '<p>BME280(I2C) + BH1750 光照，每 30s 上报。</p>'),
  ('2. 数据',cd('json','{"device":"env1","temp":25.3,"humi":60,"lux":320,"ts":1699999999}')),
  ('3. App', '<p>SwiftUI Charts 展示历史；阈值推送 Local Notification。</p>'),
  ('4. 深度', '<p>加 Deep Sleep 电池版；云端 InfluxDB 存时序。</p>')], 
 'JSON schema 固件 App 统一。',None,
 [('校准?','与标准计对比。'),('离线?','本地 SD/SPIFFS 缓存。'),('多房间?','device_id 区分。')],
 ['多传感器采集','MQTT JSON','App Charts','可扩展睡眠版'],'04-蓝牙小车.html','04-小车'),
('04-蓝牙小车.html','项目实战 04：蓝牙小车','蓝牙小车','L298N 电机+BLE 方向控制，JoyStick UI。',
 [('1. 硬件',cd('text','ESP32/STM32 + L298N + 2DC电机 + 电池')),
  ('2. 协议',cd('text','Char 0x01: [left_pwm, right_pwm] int8 -100~100')),
  ('3. App', '<p>SwiftUI Joystick → BLE write 20Hz；dead zone 防 drift。</p>'),
  ('4. 安全', '<p>超时 500ms 无指令自动停车。</p>')], 
 '电机干扰大，电源电容+去耦；BLE 天线远离电机。',None,
 [('PID?','循迹进阶。'),('Wi-Fi 版?','MQTT 远控但延迟大。'),('电池?','2S LiPo+保护。')],
 ['BLE 低延迟控车','Joystick UI','超时停车','电源去耦'],'05-农业IoT.html','05-农业'),
('05-农业IoT.html','项目实战 05：农业 IoT','农业IoT','土壤湿度+自动灌溉+太阳能+LoRa可选。',
 [('1. 传感', '<p>电容式土壤湿度 + DS18B20 水温；避免 corrosion 用电容式。</p>'),
  ('2. 控制', '<p>继电器控水泵；阈值 hysteresis 防频繁启停。</p>'),
  ('3. 供电', '<p>太阳能板 + LiFePO4 + MPPT 模块；Deep Sleep 间隔采样。</p>'),
  ('4. 云', '<p>MQTT 上报 + App 远程手动浇；本地 OLED 显示状态。</p>')], 
 '农业项目政府补贴多，作品集可接政企单。',None,
 [('电阻式腐蚀?','换电容式。'),('LoRa?','远距无 Wi-Fi 场景。'),('防水?','IP65 外壳。')],
 ['土壤+灌溉逻辑','太阳能供电','MQTT 远程','政企项目方向'],'06-工业采集.html','06-工业'),
('06-工业采集.html','项目实战 06：工业采集','工业采集','Modbus RS485 读 PLC/传感器，MQTT 上云。',
 [('1. 硬件',cd('text','STM32/ESP32 + MAX485 + RS485 总线')),
  ('2. Modbus',cd('c','// 读保持寄存器 0x0000 长度1\nuint8_t req[]={0x01,0x03,0x00,0x00,0x00,0x01,CRC_L,CRC_H};')),
  ('3. 网关', '<p>轮询多个从站 → 聚合 JSON → MQTT publish。</p>'),
  ('4. 可靠', '<p>看门狗+重连+本地 SD 断网缓存。</p>')], 
 '工业项目单价高，需稳定 7×24。',None,
 [('CRC?','Modbus RTU 必须。'),('终端电阻?','485 两端120Ω。'),('隔离?','工业用隔离 485。')],
 ['Modbus 采集网关','485 硬件','MQTT 上云','工业级可靠性'],'../应用场景/01-行业应用全景.html','应用 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in PROJ:
    ALL.append(ch(f'项目实战/{f}',t,'项目实战','项目实战',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

SCENE = [
('01-行业应用全景.html','应用 01：行业应用全景','行业全景','七大嵌入式方向与 iOS+MCU 切入建议。',
 [('1. 七大方向','<ul><li>消费电子 IoT</li><li>工业控制</li><li>汽车电子</li><li>医疗设备</li><li>智慧农业</li><li>新能源 BMS</li><li>机器人</li></ul>'),
  ('2. 对比',tbl(['方向','门槛','薪资','iOS协同'],[['IoT','低','8-20K','极高'],['工业','中','10-25K','中'],['汽车','高','15-35K','低']])),
  ('3. 建议', '<p>你背景最适合 <strong>消费电子 IoT</strong>：ESP32+App，投入小、作品集直观、接单快。</p>'),
  ('4. 趋势 2026', '<p>Edge AI、Matter 协议、车规 MCU、储能 BMS 增长。</p>')], 
 '选对方向比盲目深钻更重要。',None,
 [('转行?','IoT 全栈 3-6 个月可出作品。'),('汽车?','需 C++ AUTOSAR 深。'),('医疗?','法规严周期长。')],
 ['七大方向各有特点','IoT 最适合 iOS 背景','作品集导向','关注 Matter/Edge AI'],'02-如何接单赚钱.html','02-接单'),
('02-如何接单赚钱.html','应用 02：如何接单赚钱','接单赚钱','渠道、定价、首单路径。',
 [('1. 渠道',tbl(['渠道','单价','特点'],[['闲鱼/淘宝','500-5K','入门快'],['程序员客栈','5K-30K','项目制'],['人脉转介绍','2万+','信任溢价']])),
  ('2. 高溢价项目','<ol><li>App+硬件套装</li><li>农业监测</li><li>BLE 门禁/打印</li><li>毕设辅导</li></ol>'),
  ('3. 定价',cd('text','报价 = 工时×(300-800元/h) + 硬件成本×1.2 + 风险系数')),
  ('4. 首单', '<p>3 个 GitHub demo → 闲鱼挂「iOS+ESP32 开发」→ 首单 5 折换好评案例。</p>')], 
 '案例>证书，demo 视频是成交关键。',None,
 [('没案例?','先做台灯+环境监测开源。'),('合同?','里程碑 30-40-30 付款。'),('维护?','年费 15-20%。')],
 ['多渠道','iOS+硬件溢价','里程碑付款','案例先行'],'03-职业规划.html','03-职业'),
('03-职业规划.html','应用 03：职业规划','职业规划','嵌入式+iOS 双栈职业路径，学习路线与薪资。',
 [('1. 路径',tbl(['阶段','技能','目标'],[['0-3月','ESP32+BLE+App','2个demo'],['3-6月','STM32+RTOS','求职/接单'],['6-12月','OTA+项目','全栈工程师']])),
  ('2. 岗位', '<p>智能硬件工程师、IoT 全栈、嵌入式软件(iOS 协同)、创业产品负责人。</p>'),
  ('3. 简历', '<p>突出：独立完成固件+App 联调；GitHub；demo 链接；解决过的 hard bug。</p>'),
  ('4. 持续', '<p>Matter/HomeKit、Edge ML(TinyML)、Rust embedded 是加分项。</p>')], 
 'T 型人才：iOS 深 + MCU 够用宽。',None,
 [('纯嵌入式?','可，但 iOS 是差异化。'),('管理岗?','5年+项目经验。'),('创业?','小批量验证再投。')],
 ['分阶段目标','智能硬件岗位','作品集简历','T 型双栈'],'../练习/01-入门采购清单.html','练习 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in SCENE:
    ALL.append(ch(f'应用场景/{f}',t,'应用场景','应用场景',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

# 练习 3 + 面试 2
_quiz_qa = [
('MCU 和 CPU 的区别？','MCU 集成 CPU+Flash+RAM+外设；CPU 只是运算核心。'),
('GPIO 推挽和开漏区别？','推挽可输出高低；开漏只能拉低或高阻，需上拉。'),
('I2C 为什么用上拉？','开漏输出只能拉低，释放时靠上拉拉高。'),
('BLE Central 和 Peripheral？','Central 发起连接(通常是手机)；Peripheral 广播被连(设备)。'),
('volatile 作用？','防止编译器优化掉对寄存器的重复读取。'),
('FreeRTOS 任务和线程？','类似，有独立栈和优先级，由调度器抢占。'),
('UART 115200 含义？','每秒 115200 比特，常见 8N1 配置。'),
('ESP32 Deep Sleep 功耗？','约 10µA 级，RAM 丢失，RTC 内存可保留。'),
('看门狗作用？','程序跑飞超时未喂狗则复位，提高可靠性。'),
('Modbus 功能码 03？','读保持寄存器。'),
('ADC 12bit 分辨率？','0-4095 对应 0-Vref。'),
('MQTT QoS 1 含义？','至少送达一次，可能重复。'),
('STM32 HAL_Delay 不准？','先查 SystemCoreClock 和时钟树配置。'),
('iOS CoreBluetooth 扫不到设备？','查 UUID、权限、广播、真机。'),
('指针和数组关系？','数组名是指向首元素的常量指针。'),
]
_quiz_html = ''.join(f'<h3>{i}. {q}</h3><details><summary>点击查看答案</summary><p>{a}</p></details>' for i,(q,a) in enumerate(_quiz_qa,1))

ALL.append(ch('练习/01-入门采购清单.html','练习 01：入门采购清单','练习','练习',
  rich('学习目标：200 元内采购清单，知道每项用途与购买关键词。',
    [('1. 核心清单',tbl(['物品','参考价','用途'],[['ESP32-DevKitC','¥28','主控'],['USB-C线','¥8','供电烧录'],['面包板+杜邦线','¥15','实验'],['LED+电阻+按键','¥5','GPIO'],['DHT22','¥8','传感器'],['万用表','¥30','排查'],['舵机+继电器模块','¥25','PWM/强控']])),
     ('2. 总计','<p><strong>约 ¥170</strong>，周末到货即可开干。</p>'),
     ('3. 可选升级',tbl(['可选','价'],[['逻辑分析仪','¥25'],['ST-Link+STM32','¥27'],['烙铁套装','¥40']])),
     ('4. 关键词',cd('text','淘宝搜: ESP32-DevKitC-32E 官方版\n避免: 传感器大礼包50合1'))],
    '先买核心七件，别一次买满。',None,
    [('哪家买?','淘宝/拼多多/立创商城。'),('兼容板?','可以，注意 CH340 驱动。'),('还需要?','防静电垫可选。')],
    ['170元核心清单','ESP32+DHT22+万用表','按需加 ST-Link','别买大礼包'],'02-自测题.html','02-自测')))

ALL.append(ch('练习/02-自测题.html','练习 02：自测题（15 题）','练习','练习',
  rich('学习目标：15 道自测题覆盖基础到 iOS 联动，先自答再展开，8 分及格。',
    [('1. 说明','<p>涵盖 MCU 概念、GPIO、协议、BLE、FreeRTOS、iOS。建议闭卷。</p>'),
     ('2. 题目',_quiz_html),
     ('3. 评分',tbl(['得分','等级'],[['12-15','优秀，进实战'],['8-11','及格，补薄弱章'],['<8','重读基础模块']]))],
    '错题回到对应章节动手实验。',None,
    [('只做题?','必须配合 DevKit。'),('15题够?','入门检测足够。'),('iOS 题?','12-15 涉及联动。')],
    ['15题含details答案','8分及格','覆盖全模块','错题回章节'],'03-12周学习计划.html','03-计划')))

ALL.append(ch('练习/03-12周学习计划.html','练习 03：12 周学习计划','练习','练习',
  rich('学习目标：12 周从点灯到 2 个完整项目+面试准备，每周可检验产出。',
    [('1. 总览',cd('text','W1-2: 基础+C+GPIO+点灯串口\nW3-4: 入门实战10章+协议\nW5-6: STM32+ESP32\nW7-8: FreeRTOS+低功耗+OTA\nW9-10: iOS BLE/MQTT 联动\nW11-12: 2项目+面试题')),
     ('2. 每周细节',tbl(['周','目标','产出'],[['1','环境+点灯','Blink 视频'],['4','完成入门实战','串口日志合集'],['8','STM32+ESP32','双平台 demo'],['10','App 控灯','TestFlight 内测'],['12','台灯+环境项目','GitHub+简历']])),
     ('3. 时间', '<p>每周至少 5 小时；在职可拉长到 16 周。</p>'),
     ('4. 检验', '<p>每章：代码 commit + 串口截图；每项目：1 分钟 demo 视频。</p>')],
    '动手>看书，产出>笔记。',None,
    [('兼职?','5h/周可行。'),('跳过STM32?','求职建议别跳。'),('项目选?','台灯+环境监测。')],
    ['12周结构化','每周可检验产出','5h/周最低','作品集导向'],'../面试题/01-嵌入式基础50题.html','面试题')))

_base_q = [
('什么是 MCU？','集成 CPU、存储、外设的单芯片控制器，面向嵌入式控制。'),
('Flash 和 RAM 区别？','Flash 掉电保持存程序；RAM 掉电丢失存变量。'),
('解释 GPIO 推挽输出。','内部 PMOS+NMOS 可主动输出高或低。'),
('什么是中断？','硬件事件打断 CPU 执行 ISR，再返回。'),
('UART 需要几根线？','至少 TX/RX/GND 三根。'),
('I2C 总线两根线叫什么？','SDA 数据线、SCL 时钟线。'),
('SPI 片选 CS 作用？','多从设备时选择当前通信对象。'),
('什么是波特率？','串口每秒传输的符号数，常用 115200。'),
('指针是什么？','存放内存地址的变量。'),
('volatile 关键字？','告诉编译器不要优化对该变量的访问。'),
('堆和栈区别？','栈自动管理局部变量；堆 malloc 手动 free。'),
('什么是 PWM？','脉宽调制，用占空比模拟模拟量或控舵机。'),
('ADC 作用？','模拟电压转数字量。'),
('看门狗 IWDG 作用？','超时复位防程序跑飞。'),
('CAN 总线特点？','差分、多主、抗干扰，汽车常用。'),
('Modbus RTU 物理层？','通常 RS485。'),
('BLE GATT 三层？','Service → Characteristic → Descriptor。'),
('Notify 和 Read 区别？','Notify 设备主动推；Read 主机主动读。'),
('FreeRTOS Task 创建函数？','xTaskCreate。'),
('Mutex 解决什么问题？','多任务访问共享资源互斥，防竞态。'),
('Queue 用途？','任务间安全传递数据。'),
('ESP32 Deep Sleep 唤醒方式？','定时器、GPIO、RTC 等。'),
('NVS 是什么？','ESP32 非易失键值存储。'),
('OTA 双分区目的？','升级失败可回滚旧固件。'),
('STM32 HAL 和 LL？','HAL 抽象易用；LL 接近寄存器高效。'),
('CubeMX 作用？','图形化配引脚时钟并生成初始化代码。'),
('SWD 几根线？','SWDIO/SWCLK/GND/3.3V。'),
('Brownout 复位？','供电电压过低时 MCU 复位保护。'),
('上拉电阻作用？','为开漏/输入提供默认高电平。'),
('逻辑分析仪用途？','抓取数字时序，解码 I2C/SPI/UART。'),
('MQTT pub/sub？','发布订阅模式，解耦设备与 App。'),
('QoS 0/1/2 区别？','0 最多一次；1 至少一次；2 恰好一次。'),
('WiFi STA 模式？','Station 连接现有路由器。'),
('3.3V 和 5V GPIO 能混接吗？','不能，5V 进 3.3V GPIO 会损坏。'),
('struct 和 class？','C 的 struct 无方法默认；C++ struct 可含方法。'),
('位操作置位公式？','reg |= (1 << n)。'),
('Mem_Read I2C？','HAL_I2C_Mem_Read 带寄存器地址读。'),
('DMA 好处？','外设与内存直传，减 CPU 占用。'),
('Tickless Idle？','空闲时停 SysTick 进低功耗。'),
('Bootloader 作用？','上电加载/升级 App 固件。'),
('MISRA C？','汽车等安全关键领域的 C 编码规范子集。'),
('CoreBluetooth Central？','iPhone 扫描连接外设的角色。'),
('NSBluetoothAlwaysUsageDescription？','iOS 蓝牙权限说明，必填。'),
('SmartConfig 是什么？','手机通过 Wi-Fi 编码广播 SSID 给 ESP。'),
('CocoaMQTT 用途？','iOS MQTT 客户端库。'),
('HomeKit 门槛？','MFi 认证，门槛高于自建 BLE。'),
('Edge AI on MCU？','TinyML 在 MCU 跑推理，如唤醒词。'),
('Matter 协议？','智能家居互操作标准，基于 IP。'),
('Resume 嵌入式项目怎么写？','量化：独立完成固件+App，写了什么协议，解决什么 bug。'),
('如何排查 HardFault？','看 LR/PC，查 CFSR/HFSR，用 GDB 反汇编。'),
]
_base_html = ''.join(f'<h3>{i}. {q}</h3><details><summary>参考答案</summary><p>{a}</p></details>' for i,(q,a) in enumerate(_base_q,1))

ALL.append(ch('面试题/01-嵌入式基础50题.html','面试题 01：嵌入式基础 50 题','面试题','面试题',
  rich('学习目标：50 道嵌入式基础面试题含参考答案，覆盖 MCU/GPIO/协议/C/RTOS。',
    [('1. 使用说明','<p>先自答再展开。校招/社招基础岗常从中抽 5-10 题。</p>'),
     ('2. 题目与答案',_base_html),
     ('3. 高频考点',tbl(['考点','频率'],[['中断与优先级','极高'],['I2C/SPI/UART','高'],['指针/volatile','高'],['FreeRTOS IPC','中高']]))],
    '理解+项目例子>死记硬背。',None,
    [('50题全背?','不必，理解为主。'),('不会怎么办?','诚实+学习意愿+相关经验。'),('手写代码?','可能让写 GPIO/队列伪代码。')],
    ['50题含details答案','覆盖基础高频','结合项目举例','诚实应对'],'02-进阶与iOS联动30题.html','02-进阶30题')))

_adv_q = [
('FreeRTOS 优先级反转及解决？','低优先级持 Mutex 时高优先级等待；用优先级继承 Mutex。'),
('xQueueSendFromISR 注意？','仅 ISR 内用，可能触发 yield。'),
('ESP32 双核如何分工？','PRO 常跑 Wi-Fi/BT 协议栈，APP 跑用户代码。'),
('NimBLE vs Bluedroid？','NimBLE 省 RAM，IDF 5 默认推荐。'),
('TLS 证书校验 OTA？','HTTPS OTA 验证 server 证书或 embed 公钥。'),
('Tickless 配置项？','configUSE_TICKLESS_IDLE 及 portSUPPRESS_TICKS。'),
('JTAG 和 SWD？','SWD 是 ARM 2线调试接口，JTAG 4/5 线更通用。'),
('Mem manage heap_4？','FreeRTOS 带合并的 heap 算法。'),
('ADC DMA 双缓冲？','半完成/全完成回调交替处理，无丢失。'),
('Modbus CRC 计算？','RTU 帧尾 16 位 CRC，低字节在前。'),
('CAN 扩展帧？','29 位 ID vs 标准 11 位。'),
('BLE 配对 vs 绑定？','配对建立加密；绑定保存密钥下次直连。'),
('MTU 交换流程？','连接后 requestMtu，双方协商更大 payload。'),
('iOS 后台 BLE 限制？','需 bluetooth-central；扫描受限；Notify 可唤醒。'),
('State Restoration 场景？','App 被杀后系统恢复 CB 状态与连接。'),
('NEHotspotConfiguration？','iOS 帮设备连指定 Wi-Fi（能力有限）。'),
('MQTT retained message？','Broker 保留最后一条，新订阅者立即收到。'),
('WebSocket MQTT？','8884/ws 穿透某些防火墙。'),
('Matter 与 BLE？','Matter Commissioning 常用 BLE 传凭据。'),
('TinyML 框架？','TensorFlow Lite Micro、Edge Impulse。'),
('Rust embedded 优势？','内存安全、无 NULL、现代工具链。'),
('Functional Safety ISO 26262？','汽车功能安全标准。'),
('CE/FCC 认证？','欧盟/美国无线电与 EMC 合规。'),
('LCSC vs Digikey？','LCSC 国内快便宜；Digikey 全但贵。'),
('PCBA 代工？','嘉立创 PCBA 小批量贴片。'),
('Scope vs Logic Analyzer？','示波器看 analog 波形；逻辑分析仪 decode 数字协议。'),
('RTT 调试？','SEGGER Real-Time Transfer 无串口 log。'),
('Unit test Unity？','C 单元测试框架，测纯算法。'),
('Git submodule 固件？','第三方库版本锁定。'),
('CI for firmware？','PlatformIO CI 编译+静态分析+硬件在环(可选)。'),
]
_adv_html = ''.join(f'<h3>{i}. {q}</h3><details><summary>参考答案</summary><p>{a}</p></details>' for i,(q,a) in enumerate(_adv_q,1))

ALL.append(ch('面试题/02-进阶与iOS联动30题.html','面试题 02：进阶与 iOS 联动 30 题','面试题','面试题',
  rich('学习目标：30 道进阶+ iOS 联动面试题含答案，RTOS/OTA/BLE/MQTT/全栈。',
    [('1. 说明','<p>中高级与智能硬件全栈岗。每题准备：原理+项目例子+踩坑。</p>'),
     ('2. 题目与答案',_adv_html),
     ('3. 回答模板',cd('text','是什么 → 为什么 → 项目中怎么用 → 踩过什么坑'))],
    '项目经验比背题更能打动面试官。',None,
    [('iOS 岗考 MCU?','智能硬件/IoT 岗会考。'),('RTOS 深度?','IPC/优先级常考。'),('系统设计?','可能画架构图。')],
    ['30题进阶+iOS','含details答案','原理+项目+踩坑','全栈差异化'])))

print('Part3 total ALL', len(ALL))
