#!/usr/bin/env python3
"""Part 2: 硬件(6) + 协议(8) + 入门实战(10)"""
from _gen_part1 import rich, ch, tbl, cd, ALL

HW = [
('01-开发板与工具.html','硬件 01：开发板与工具','开发板工具','认识开发板组成，配齐工具，完成 Blink。',
 [('1. 开发板是什么','<p>MCU + 最小外围（晶振、LDO、USB-UART、LED/按键）+ 排针。降低入门门槛。</p>'),
  ('2. 类型对比',tbl(['类型','代表','特点'],[['Wi-Fi/BLE','ESP32-DevKitC','IoT 首选'],['工业','STM32 Nucleo','外设全+ST-Link'],['BLE','nRF52840 DK','低功耗'],['极简','Arduino Uno','16MHz 8bit']])),
  ('3. 工具清单',tbl(['工具','必须','用途'],[['ESP32 开发板','✅','主平台'],['面包板+线','✅','免焊实验'],['万用表','✅','测电压通断'],['烙铁','可选','焊接'],['逻辑分析仪','可选','协议解码']])),
  ('4. 第一次 Blink',cd('c','void setup(){ pinMode(2,OUTPUT); Serial.begin(115200);}\nvoid loop(){ digitalWrite(2,!digitalRead(2)); delay(500); Serial.println("blink");}'))],
 'ESP32-DevKitC 约30元，IoT+iOS 一块板够用。',None,
 [('开发板=芯片?','板=芯片+外围+USB。'),('Mac?','完全支持。'),('兼容板?','可以，查驱动。')],
 ['开发板降门槛','ESP32 IoT首选','万用表必备','Blink 第一步'],'02-万用表与焊接入门.html','02-万用表'),
('02-万用表与焊接入门.html','硬件 02：万用表与焊接入门','万用表焊接','万用表三板斧，焊接安全，排查短路。',
 [('1. 万用表三档',tbl(['档位','用途','ESP32 期望'],[['DC V','测电压','3.3V/5V'],['通断','测连线','蜂鸣'],['Ω','测电阻','220Ω LED']])),
  ('2. 安全红线','<ul><li>短路 VCC-GND 烧芯片</li><li>5V 进 3.3V GPIO 永久损坏</li><li>锂电池必须保护板</li><li>220V 继电器用合规模块</li></ul>'),
  ('3. 焊接五步',cd('text','1.烙铁350°C 2.加热焊盘 3.送锡 4.停2秒 5.移烙铁')),
  ('4. 虚焊排查','<p>通断档测焊点；LED 不亮先测 GPIO 电压。</p>')],
 '先练废板再焊项目。','锂电池必须保护板，勿短路。',
 [('表笔接法?','黑GND红测点。'),('虚焊?','通断档+晃动看阻值。'),('焊锡?','0.8mm 含铅易上手。')],
 ['万用表三板斧','ESP32仅3.3V','安全红线牢记','焊接需练习'],'03-原理图阅读入门.html','03-原理图'),
('03-原理图阅读入门.html','硬件 03：原理图阅读入门','原理图','读原理图定位引脚，符号识别，四步阅读法。',
 [('1. 为何重要','<p>原理图 = 硬件 API 文档。不知道 GPIO2 接什么，代码写对也白搭。</p>'),
  ('2. 符号',tbl(['符号','含义'],[['R','电阻'],['C','电容'],['D/LED','二极管/LED'],['U','芯片'],['VCC/GND','电源地']])),
  ('3. 四步阅读',cd('text','1.找MCU芯片 2.看电源树(LDO/去耦) 3.跟GPIO到外围 4.看通信(UART/I2C)')),
  ('4. 获取途径','<p>厂商 GitHub/Wiki、立创EDA 开源、DevKit PDF 随板附赠。</p>')],
 'PDF 对照实物板最快建立空间感。',None,
 [('哪下载?','乐鑫/ST 官网 GitHub。'),('GPIO2=LED?','以原理图为准。'),('立创EDA?','免费在线画/看。')],
 ['原理图是硬件API','先MCU后电源','GPIO查图不猜','立创EDA开源多'],'04-PCB入门.html','04-PCB'),
('04-PCB入门.html','硬件 04：PCB 入门','PCB入门','面包板拓扑，PCB 术语，打样流程。',
 [('1. 面包板', '<p>中间槽两侧不通，上下轨连通。适合 MHz 以下原型。</p>'),
  ('2. PCB 术语', tbl(['术语','含义'],[['丝印','白色文字标识'],['铜箔','走线导电'],['过孔','层间连接'],['焊盘','元件焊接点']])),
  ('3. 设计流程', '<ol><li>原理图</li><li>PCB 布局</li><li>DRC 检查</li><li>嘉立创打样</li></ol>'),
  ('4. 何时上 PCB', '<p>面包板验证功能后；频率>1MHz 或要量产时。</p>')], 
 '验证后 PCB，几十元打样 5 片。',None,
 [('面包板极限?','高频/大电流需PCB。'),('打样费?','5片几十元包邮。'),('飞线?','调试补线技巧。')],
 ['面包板做实验','验证后PCB','懂丝印过孔焊盘','嘉立创打样便宜'],'05-电源设计.html','05-电源'),
('05-电源设计.html','硬件 05：电源设计','电源设计','LDO/DC-DC，ESP32 供电，去耦与 Brownout。',
 [('1. 电源树',cd('text','USB 5V → LDO(AMS1117-3.3) → 3.3V → ESP32\n         → 100nF+10µF 去耦')),
  ('2. LDO vs DC-DC',tbl(['类型','优点','缺点'],[['LDO','简单低纹波','效率低发热'],['DC-DC','高效','纹波/EMI复杂']])),
  ('3. ESP32 峰值', '<p>Wi-Fi 发射瞬间可达 500mA+，USB 500mA 够用但 LDO 需散热，建议 1117-1A 以上。</p>'),
  ('4. Brownout', '<p>电压过低芯片复位。电池项目注意放电曲线+低压检测。</p>')],
 '供电不稳表现为 Wi-Fi 断连、ADC 跳变、随机复位。','锂电池必须保护板。',
 [('Brownout?','低压自动复位保护。'),('电池方案?','LiPo+保护板+LDO。'),('纹波影响?','干扰 Wi-Fi/ADC。')],
 ['供电是基础','Wi-Fi峰值500mA','去耦电容必须','电池加保护板'],'06-元件选型.html','06-选型'),
('06-元件选型.html','硬件 06：元件选型','元件选型','MCU/传感器/被动件 BOM 选型，LCSC 供货。',
 [('1. MCU 选型',tbl(['需求','推荐'],[['IoT+App','ESP32-S3'],['工业','STM32F407'],['超低功耗','nRF52840']])),
  ('2. 传感器',tbl(['功能','型号','接口'],[['温湿度','DHT22/BME280','单总线/I2C'],['距离','HC-SR04','GPIO'],['光照','BH1750','I2C'],['屏','SSD1306','I2C']])),
  ('3. BOM 示例',tbl(['位号','型号','说明'],[['U1','ESP32-WROOM','主控'],['U2','AMS1117-3.3','LDO'],['R1','220Ω','LED限流']])),
  ('4. 模块 vs 芯片', '<p>原型用模块（DHT 模块、继电器模块）快；量产用芯片降 BOM。</p>')],
 'LCSC 查库存+下载 datasheet 是工程师日常。',None,
 [('LCSC?','立创商城元器件。'),('0805?','贴片封装尺寸。'),('模块优势?','免焊接快速验证。')],
 ['先列需求再选型','原型用模块','LCSC查库存','BOM留20%余量'],'../入门实战/01-第一个程序点灯.html','入门实战'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in HW:
    ALL.append(ch(f'硬件/{f}',t,'硬件入门','硬件',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

PROTO = [
('01-UART详解.html','协议 01：UART 详解','UART','UART 帧格式、波特率、接线、ESP32/STM32 收发。',
 [('1. 基础',tbl(['参数','典型值'],[['波特率','115200'],['数据位','8'],['停止位','1'],['校验','None']])),
  ('2. 接线',cd('text','MCU TX → 模块 RX\nMCU RX → 模块 TX\nGND 必须共地')),
  ('3. ESP32 代码',cd('c','Serial.begin(115200);\nSerial.printf("Chip: %s\\n", ESP.getChipModel());\nwhile(Serial.available()) {\n  char c = Serial.read();\n  Serial.write(c); // echo\n}')),
  ('4. 应用', '<p>调试 NSLog 级、GPS NMEA、蓝牙 AT 指令、Modbus RTU 物理层。</p>')],
 'TX/RX 交叉，必须共 GND。',None,
 [('乱码?','波特率不一致。'),('USB-TTL?','无 USB 的板子需要。'),('printf 重定向?','_write 或 HAL_UART_Transmit。')],
 ['UART两线全双工','115200最常用','TXRX交叉共地','嵌入式NSLog'],'02-I2C详解.html','02-I2C'),
('02-I2C详解.html','协议 02：I2C 详解','I2C','I2C 时序、地址、开漏上拉、OLED 驱动。',
 [('1. 时序','<p>START → 7位地址+W/R → ACK → 数据字节 → ACK → STOP</p>'),
  ('2. 参数',tbl(['项','值'],[['标准速率','100kHz'],['快速','400kHz'],['地址','7位(0x03C OLED)'],['上拉','4.7kΩ']])),
  ('3. 扫描代码',cd('c','Wire.begin(21,22);\nfor(byte a=1;a<127;a++){\n  Wire.beginTransmission(a);\n  if(!Wire.endTransmission()) Serial.printf("0x%02X\\n",a);\n}')),
  ('4. OLED 初始化',cd('c','display.begin(SSD1306_SWITCHCAPVCC, 0x3C);\ndisplay.clearDisplay();\ndisplay.setTextSize(1);\ndisplay.println("Hello iOS Dev");\ndisplay.display();'))],
 '开漏+上拉，多设备共 SDA/SCL。',None,
 [('无ACK?','地址错/未上电/无上下拉。'),('clock stretching?','从机拉低SCL等待。'),('3.3V 5V?','需电平转换。')],
 ['I2C两线多主','开漏必须上拉','7位地址查手册','扫描找设备'],'03-SPI详解.html','03-SPI'),
('03-SPI详解.html','协议 03：SPI 详解','SPI','SPI 四线、模式 CPOL/CPHA、CS 片选、Flash 驱动。',
 [('1. 信号',tbl(['线','方向','作用'],[['MOSI','主→从','主发数据'],['MISO','从→主','从发数据'],['SCK','主→从','时钟'],['CS','主→从','片选']])),
  ('2. 四种模式',tbl(['模式','CPOL','CPHA'],[['0','0','0'],['1','0','1'],['2','1','0'],['3','1','1']])),
  ('3. 代码',cd('c','SPI.beginTransaction(SPISettings(1000000, MSBFIRST, SPI_MODE0));\ndigitalWrite(CS, LOW);\nSPI.transfer(0x03); // read cmd\nbyte b = SPI.transfer(0xFF);\ndigitalWrite(CS, HIGH);')),
  ('4. vs I2C',tbl(['','I2C','SPI'],[['线数','2','4+'],['速度','慢','快'],['寻址','地址字节','CS引脚']]))],
 '模式必须对照 slave datasheet。',None,
 [('比I2C快?','是，无地址开销。'),('CS 作用?','多设备独立片选。'),('3线SPI?','无MISO只写。')],
 ['SPI四线全双工','CPOL/CPHA看手册','CS选设备','Flash/屏常用'],'04-CAN总线入门.html','04-CAN'),
('04-CAN总线入门.html','协议 04：CAN 总线入门','CAN','CAN 帧、仲裁、终端电阻、汽车工控。',
 [('1. 特点','<p>差分总线 CAN_H/CAN_L，多主，抗干扰，传输距离远。汽车/工控标准。</p>'),
  ('2. 标准帧',tbl(['场','说明'],[['ID','11位优先级仲裁'],['DLC','0-8字节'],['Data',' payload'],['CRC','校验']])),
  ('3. 硬件',cd('text','MCU CAN_TX/RX → TJA1050 收发器 → CAN_H/CAN_L\n总线两端各120Ω终端电阻')),
  ('4. STM32', '<p>bxCAN/FDCAN 外设 + 外部收发器。ID 越小优先级越高。</p>')], 
 '终端电阻缺一会反射导致通信失败。',None,
 [('和UART?','CAN多主差分远距。'),('120Ω?','总线两端各一个。'),('CAN FD?','更高速率更多数据。')],
 ['CAN汽车工控标准','差分抗干扰','终端120Ω','ID仲裁优先级'],'05-Modbus协议.html','05-Modbus'),
('05-Modbus协议.html','协议 05：Modbus 协议','Modbus','Modbus RTU/TCP、功能码、工业传感器。',
 [('1. 类型',tbl(['类型','物理层'],[['RTU','RS485/UART'],['TCP','以太网'],['ASCII','少见']])),
  ('2. 功能码',tbl(['码','含义'],[['03','读保持寄存器'],['06','写单寄存器'],['16','写多寄存器']])),
  ('3. RTU 帧',cd('text','[地址1B][功能码1B][起始2B][数量2B][CRC2B]\n例: 01 03 00 00 00 01 CRC')),
  ('4. 工具', '<p>Modbus Poll/Slave 调试；libmodbus 开源库；工控 PLC 标配。</p>')], 
 'CRC 小端，寄存器地址查设备手册。',None,
 [('RTU vs TCP?','RTU串口485，TCP网口。'),('免费库?','libmodbus。'),('和MQTT?','Modbus工控现场，MQTT上云。')],
 ['Modbus工业标准','RTU用RS485','功能码读写寄存器','工控传感器常见'],'06-BLE协议栈.html','06-BLE'),
('06-BLE协议栈.html','协议 06：BLE 协议栈','BLE协议栈','GAP/GATT、广播连接、Service/Characteristic、MTU。',
 [('1. 角色',tbl(['角色','设备','iOS API'],[['Central','手机','CBCentralManager'],['Peripheral','ESP32','CBPeripheralManager(少见)']])),
  ('2. GATT 层次',cd('text','Profile → Service(0x180F Battery) → Characteristic(0x2A19 Level) → Descriptor')),
  ('3. 连接流程','<ol><li>Peripheral 广播</li><li>Central 扫描</li><li>connect</li><li>discoverServices</li><li>read/write/notify</li></ol>'),
  ('4. ESP32 NimBLE',cd('c','NimBLEDevice::init("MyLamp");\nNimBLEService *svc = server->createService(SERVICE_UUID);\nNimBLECharacteristic *ch = svc->createCharacteristic(CHAR_UUID, NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY);'))],
 'iOS 开发者先掌握 GATT 层即可开发 90% 产品。',None,
 [('配对绑定?','配对加密，绑定存LTK。'),('Notify?','设备主动推送，类似 WebSocket。'),('MTU?','协商更大包减开销。')],
 ['Central/Peripheral','GATT结构清晰','Notify推数据','iOS先学GATT'],'07-WiFi与TCP.html','07-WiFi'),
('07-WiFi与TCP.html','协议 07：WiFi 与 TCP','WiFi TCP','STA/AP 模式、TCP/UDP Socket、ESP32 联网。',
 [('1. WiFi 模式',tbl(['模式','用途'],[['STA','连路由器上网'],['AP','设备做热点'],['STA+AP','SmartConfig配网']])),
  ('2. TCP vs UDP',tbl(['','TCP','UDP'],[['可靠','是','否'],['有序','是','否'],['场景','HTTP/MQTT','发现/mDNS']])),
  ('3. ESP32 STA',cd('c','WiFi.begin(ssid, pass);\nwhile(WiFi.status()!=WL_CONNECTED) delay(500);\nSerial.println(WiFi.localIP());')),
  ('4. TCP Client',cd('c','WiFiClient client;\nclient.connect("192.168.1.100", 8080);\nclient.println("GET /status HTTP/1.0\\r\\n\\r\\n");'))],
 'ESP32 多数仅 2.4GHz。',None,
 [('2.4G only?','ESP32经典款是。'),('断线?','loop检查WiFi.status重连。'),('静态IP?','WiFi.config。')],
 ['STA连路由AP配网','TCP可靠UDP快','WiFi.status监测','Socket类似URLSession'],'08-MQTT协议.html','08-MQTT'),
('08-MQTT协议.html','协议 08：MQTT 协议','MQTT','pub/sub、QoS、主题设计、ESP32+iOS 三方。',
 [('1. 模型',cd('text','ESP32 --publish--> Broker <--subscribe-- iOS App\n                <--publish---        ---subscribe--> ESP32')),
  ('2. QoS',tbl(['级别','语义'],[['0','最多一次'],['1','至少一次'],['2','恰好一次']])),
  ('3. 主题设计',cd('text','home/{device_id}/sensor/temp\nhome/{device_id}/cmd/power\nhome/{device_id}/status/online')),
  ('4. 库',tbl(['端','库'],[['ESP32','PubSubClient/async_mqtt'],['iOS','CocoaMQTT/Native MQTT5'],['Broker','EMQX/Mosquitto']]))],
 '生产环境 MQTT 必须 TLS。',None,
 [('自建Broker?','开发用EMQX Docker。'),('vs HTTP?','MQTT轻量长连接pub/sub。'),(' retained?','Broker保留最后一条。')],
 ['pub/sub解耦','QoS1常用','主题分层设计','MCU+Broker+App'],'../入门实战/01-第一个程序点灯.html','入门实战'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in PROTO:
    ALL.append(ch(f'协议/{f}',t,'协议模块','协议',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

PRAC = [
('01-第一个程序点灯.html','入门实战 01：第一个程序点灯','点灯','GPIO 输出 Blink，建立烧录-运行闭环。',
 [('1. 目标','<p>点亮 LED 并闪烁，串口打印确认程序运行。</p>'),
  ('2. 接线',cd('text','ESP32 板载 LED 通常 GPIO2 或 GPIO8，查 DevKit 原理图\n外接: 3.3V─220Ω─LED─GPIO')),
  ('3. 代码',cd('c','#define LED 2\nvoid setup(){ pinMode(LED,OUTPUT); Serial.begin(115200); Serial.println("start");}\nvoid loop(){ digitalWrite(LED,HIGH); delay(500); digitalWrite(LED,LOW); delay(500);}')),
  ('4. 排错',tbl(['现象','检查'],[['不亮','LED极性/引脚号'],['不闪','程序是否跑/看串口'],['烧录失败','端口/BOOT键']]))],
 '第一个里程碑：看到 LED 闪 = 闭环成立。',None,
 [('GPIO 选哪个?','查 strapping 脚避免。'),('3.3V?','ESP32 GPIO 仅 3.3V。'),('delay 阻塞?','入门可用，后面用定时器。')],
 ['点灯=Hello World','查原理图引脚','串口确认运行','建立烧录闭环'],'02-按键与中断.html','02-按键'),
('02-按键与中断.html','入门实战 02：按键与中断','按键中断','INPUT_PULLUP、外部中断、防抖。',
 [('1. 原理','<p>按键一端 GPIO 一端 GND，内部上拉，按下读 LOW。</p>'),
  ('2. 中断代码',cd('c','volatile bool pressed=false;\nvoid IRAM_ATTR isr(){ pressed=true; }\nvoid setup(){ pinMode(15,INPUT_PULLUP); attachInterrupt(digitalPinToInterrupt(15),isr,FALLING);}\nvoid loop(){ if(pressed){ pressed=false; delay(10); if(digitalRead(15)==LOW) Serial.println("key");}}')),
  ('3. vs 轮询', '<p>轮询浪费 CPU；中断事件驱动，类似 UIControlEvents。</p>'),
  ('4. 消抖', '<p>硬件 RC 或软件 delay 10ms 再确认。</p>')], 
 '避开 strapping 脚 GPIO0/2/15 等。',None,
 [('抖动?','delay消抖。'),('ISR 规则?','短、无delay。'),('长按?','定时器计时长。')],
 ['上拉输入读低','中断事件驱动','ISR置标志主循环处理','消抖必须'],'03-串口调试.html','03-串口'),
('03-串口调试.html','入门实战 03：串口调试','串口','115200 printf 调试，格式化输出传感器值。',
 [('1. 初始化',cd('c','Serial.begin(115200);\nwhile(!Serial) delay(10); // USB CDC 等待')),
  ('2. 格式化',cd('c','Serial.printf("[%.1fs] temp=%.1f humi=%.1f\\n", millis()/1000.0, t, h);')),
  ('3. 命令行',cd('c','if(Serial.available()){\n  String cmd=Serial.readStringUntil(\'\\n\');\n  if(cmd=="on") digitalWrite(LED,HIGH);\n}')),
  ('4. iOS 类比', '<p>Serial.printf = NSLog；串口监视器 = Xcode Console。</p>')],
 '串口是嵌入式最重要的调试手段。',None,
 [('乱码?','波特率115200一致。'),('printf 浮点?','Arduino 需启用。'),('太多 log?','分级宏 DEBUG_LOG。')],
 ['115200标准','printf格式化','可做成CLI','=嵌入式NSLog'],'04-PWM控制舵机.html','04-PWM'),
('04-PWM控制舵机.html','入门实战 04：PWM 控制舵机','PWM舵机','50Hz PWM，脉宽 1-2ms 控制角度。',
 [('1. 原理','<p>舵机靠 50Hz 方波脉宽定角度：1ms≈0°，1.5ms≈90°，2ms≈180°。</p>'),
  ('2. 接线',cd('text','舵机: 红VCC(5V) 棕GND 橙信号→GPIO\n注意: 大舵机需外接5V供电')),
  ('3. 代码',cd('c','#include <ESP32Servo.h>\nServo sv; sv.attach(18); sv.write(90); // 90度\n// LEDC 底层: 50Hz, duty 1.5ms')),
  ('4. 应用', '<p>云台、机械臂、智能台灯角度、阀门。</p>')],
 '舵机供电不要从 3.3V GPIO 取 5V。','大电流舵机必须外接 5V 电源共地。',
 [('抖动?','供电不足加电容。'),('角度不准?','calibrate min/max pulse。'),('多个舵机?','LEDC 多通道。')],
 ['50Hz脉宽控角','1-2ms映射0-180','注意5V供电','LEDC/PWM外设'],'05-温湿度传感器.html','05-温湿度'),
('05-温湿度传感器.html','入门实战 05：温湿度传感器','温湿度','DHT22 单总线时序，BME280 I2C 对比。',
 [('1. DHT22',cd('c','#include <DHT.h>\nDHT dht(4, DHT22);\nvoid setup(){ dht.begin();}\nvoid loop(){ float t=dht.readTemperature(); float h=dht.readHumidity();\n  if(isnan(t)) Serial.println("read fail"); else Serial.printf("T=%.1f H=%.1f\\n",t,h); delay(2000);}')),
  ('2. 接线',cd('text','DHT: VCC GND DATA→GPIO4 + 4.7k上拉(模块自带)')),
  ('3. BME280', '<p>I2C 接口，可同时气压，精度更高，驱动更简单。</p>'),
  ('4. 上云', '<p>读数 → MQTT publish → iOS 图表展示，完整数据链路。</p>')], 
 'DHT 时序严格，读间隔≥2s。',None,
 [('NaN?','接线/上拉/时序。'),('DHT11 vs 22?','22精度高。'),('校准?','与标准温湿度计对比。')],
 ['DHT单总线时序','BME280 I2C更稳','读间隔≥2s','可MQTT上云'],'06-ADC采样.html','06-ADC'),
('06-ADC采样.html','入门实战 06：ADC 采样','ADC','12bit ADC 读电位器，映射 PWM/亮度。',
 [('1. 原理','<p>ESP32 ADC 12bit (0-4095)，STM32 通常 12bit。模拟→数字。</p>'),
  ('2. 代码',cd('c','int raw = analogRead(34); // ADC1 通道\nfloat volt = raw / 4095.0 * 3.3;\nint brightness = map(raw, 0, 4095, 0, 255);\nanalogWrite(LED_PIN, brightness);')),
  ('3. 注意',tbl(['项','说明'],[['衰减','11dB 量程0-3.3V'],['ADC2','Wi-Fi时部分不可用'],['校准','esp_adc_cal']])),
  ('4. 应用', '旋钮调光、电池电压监测、光照强度。')],
 'ADC 引脚只能输入，不能当 GPIO 输出。',None,
 [('不准?','校准/参考电压。'),('噪声?','软件平均多次采样。'),('STM32?','HAL_ADC_Start+PollForConversion。')],
 ['12bit 0-4095','map映射业务值','注意衰减量程','可驱动PWM调光'],'07-OLED显示.html','07-OLED'),
('07-OLED显示.html','入门实战 07：OLED 显示','OLED','SSD1306 I2C 128x64，Adafruit 库显示温湿度。',
 [('1. 接线',cd('text','OLED: VCC GND SCL SDA → GPIO22/21\nI2C 地址通常 0x3C')),
  ('2. 代码',cd('c','#include <Adafruit_SSD1306.h>\nAdafruit_SSD1306 display(128,64,&Wire,-1);\ndisplay.begin(SSD1306_SWITCHCAPVCC,0x3C);\ndisplay.setCursor(0,0); display.printf("T:%.1fC",t); display.display();')),
  ('3. 刷新', '<p>display.display() 刷新整屏；局部刷新可优化速度。</p>'),
  ('4. vs App', '<p>OLED 本地 UI；复杂 UI 仍用 iOS App，OLED 做状态屏。</p>')], 
 'I2C 扫描确认 0x3C/0x3D 地址。',None,
 [('不显示?','地址/接线/初始化。'),('花屏?','复位时序/供电。'),('中文?','取模字库或 u8g2。')],
 ['SSD1306 I2C','128x64足够状态','Adafruit/u8g2库','本地小屏UI'],'08-EEPROM存储.html','08-EEPROM'),
('08-EEPROM存储.html','入门实战 08：EEPROM 存储','EEPROM','Preferences/NVS 掉电保存计数与配置。',
 [('1. 需求','<p>保存 Wi-Fi 凭据、亮度档位、累计运行时间——类似 UserDefaults。</p>'),
  ('2. ESP32 Preferences',cd('c','Preferences p; p.begin("myapp", false);\np.putString("ssid", ssid);\np.putInt("boot", p.getInt("boot",0)+1);\nString s = p.getString("ssid", "");')),
  ('3. STM32', '<p>Flash 末尾划 EEPROM 区，或外接 I2C EEPROM(24C02)。</p>'),
  ('4. 寿命', '<p>Flash 擦写有限(~10万次)，频繁写入需 wear leveling。</p>')], 
 '键名命名规范，begin/end 成对。',None,
 [('和 Flash 程序?','不同分区。'),('清空?','p.clear() 或 erase。'),('加密?','NVS 可加密分区。')],
 ['NVS=UserDefaults','掉电保持','注意擦写寿命','存Wi-Fi/配置'],'09-继电器控制.html','09-继电器'),
('09-继电器控制.html','入门实战 09：继电器控制','继电器','低电平触发模块，MOSFET 驱动，MQTT 远程开关。',
 [('1. 模块', '<p>光耦隔离继电器模块：IN 接 GPIO，COM/NO/NC 接负载。多数低电平触发。</p>'),
  ('2. 代码',cd('c','#define RELAY 26\npinMode(RELAY, OUTPUT);\ndigitalWrite(RELAY, LOW);  // 吸合(视模块而定)\n// MQTT: if(topic.endsWith("/power")) digitalWrite(RELAY, payload=="ON"?LOW:HIGH);')),
  ('3. 安全', '<p>220V 必须用合格模块+绝缘；勿裸手碰强电。原型用 5V 灯泡/风扇。</p>'),
  ('4. 续流', '<p>直驱继电器线圈需并联二极管；模块已集成。</p>')], 
 '强电项目找电工，勿自行冒险。','220V 必须用合规范模块，里程碑付款前做安全评审。',
 [('低电平触发?','看模块说明。'),('GPIO 电流不够?','用模块或三极管。'),('反馈状态?','读辅助触点或电流传感器。')],
 ['光耦隔离安全','低/高电平看模块','220V合规','MQTT远程控'],'10-超声波测距.html','10-超声波'),
('10-超声波测距.html','入门实战 10：超声波测距','超声波','HC-SR04 Trig/Echo，pulseIn 算距离。',
 [('1. 原理','<p>Trig 发 10µs 脉冲，Echo 高电平时间 ∝ 距离。声速340m/s，距离=时间µs/58 cm。</p>'),
  ('2. 代码',cd('c','#define TRIG 5\n#define ECHO 18\nvoid measure(){\n  digitalWrite(TRIG,LOW); delayMicroseconds(2);\n  digitalWrite(TRIG,HIGH); delayMicroseconds(10); digitalWrite(TRIG,LOW);\n  long us = pulseIn(ECHO, HIGH, 30000);\n  if(us==0) Serial.println("timeout");\n  else Serial.printf("dist=%.1f cm\\n", us/58.0);\n}')),
  ('3. 局限', '<p>Soft 材料/角度吸收；近距盲区 ~2cm；实时性受 sound speed 限制。</p>'),
  ('4. 项目', '停车辅助、垃圾桶满度、智能门锁接近检测。')], 
 'Echo 5V 时 ESP32 需分压到 3.3V。','HC-SR04 Echo 5V 输出需 1k/2k 分压保护 ESP32。',
 [('不准?','温度补偿/多次平均。'),('timeout?','超量程或无人。'),('vs ToF?','ToF 更准更贵。')],
 ['Trig/Echo时序','pulseIn测脉宽','距离=us/58','注意5V Echo'],'../STM32/01-入门.html','STM32 01'),
]
for f,t,s,i,sec,tip,warn,faq,summ,nxt,nl in PRAC:
    ALL.append(ch(f'入门实战/{f}',t,'入门实战','入门实战',rich(i,sec,tip,warn,faq,summ,nxt,nl)))

print('Part2 done', len(ALL))
