"""Site navigation matching _build_site.py format."""

NAV = [
    {"id": "home", "title": "教程首页", "href": "README.html"},
    {"id": "base", "title": "基础", "items": [
        ('01 单片机概念', '基础/01-单片机概念.html'),
        ('02 从 iOS 开发者视角看嵌入式', '基础/02-从iOS开发者视角看嵌入式.html'),
        ('03 数电基础', '基础/03-数电基础.html'),
        ('04 模电入门', '基础/04-模电入门.html'),
        ('05 开发板怎么选', '基础/05-开发板怎么选.html'),
        ('06 C 语言速成（Swift 开发者', '基础/06-C语言速成-Swift开发者版.html'),
        ('07 指针与内存', '基础/07-指针与内存.html'),
        ('08 位操作与寄存器', '基础/08-位操作与寄存器.html'),
        ('09 GPIO 与点灯原理', '基础/09-GPIO与点灯原理.html'),
        ('10 中断与定时器', '基础/10-中断与定时器.html'),
        ('11 存储器与 Flash', '基础/11-存储器与Flash.html'),
        ('12 工具链与环境搭建', '基础/12-工具链与环境搭建.html'),
    ]},
    {"id": "hw", "title": "硬件入门", "items": [
        ('01 开发板与工具', '硬件/01-开发板与工具.html'),
        ('02 万用表与焊接入门', '硬件/02-万用表与焊接入门.html'),
        ('03 原理图阅读入门', '硬件/03-原理图阅读入门.html'),
        ('04 PCB 入门', '硬件/04-PCB入门.html'),
        ('05 电源设计', '硬件/05-电源设计.html'),
        ('06 元件选型', '硬件/06-元件选型.html'),
    ]},
    {"id": "proto", "title": "协议", "items": [
        ('01 UART 详解', '协议/01-UART详解.html'),
        ('02 I2C 详解', '协议/02-I2C详解.html'),
        ('03 SPI 详解', '协议/03-SPI详解.html'),
        ('04 CAN 总线入门', '协议/04-CAN总线入门.html'),
        ('05 Modbus 协议', '协议/05-Modbus协议.html'),
        ('06 BLE 协议栈', '协议/06-BLE协议栈.html'),
        ('07 WiFi 与 TCP', '协议/07-WiFi与TCP.html'),
        ('08 MQTT 协议', '协议/08-MQTT协议.html'),
    ]},
    {"id": "start", "title": "入门实战", "items": [
        ('01 第一个程序点灯', '入门实战/01-第一个程序点灯.html'),
        ('02 按键与中断', '入门实战/02-按键与中断.html'),
        ('03 串口调试', '入门实战/03-串口调试.html'),
        ('04 PWM 控制舵机', '入门实战/04-PWM控制舵机.html'),
        ('05 温湿度传感器', '入门实战/05-温湿度传感器.html'),
        ('06 ADC 采样', '入门实战/06-ADC采样.html'),
        ('07 OLED 显示', '入门实战/07-OLED显示.html'),
        ('08 EEPROM 存储', '入门实战/08-EEPROM存储.html'),
        ('09 继电器控制', '入门实战/09-继电器控制.html'),
        ('10 超声波测距', '入门实战/10-超声波测距.html'),
    ]},
    {"id": "stm32", "title": "STM32", "items": [
        ('01 入门', 'STM32/01-入门.html'),
        ('02 CubeMX 入门', 'STM32/02-CubeMX入门.html'),
        ('03 时钟树配置', 'STM32/03-时钟树配置.html'),
        ('04 GPIO 与 HAL', 'STM32/04-GPIO与HAL.html'),
        ('05 UART 驱动', 'STM32/05-UART驱动.html'),
        ('06 SPI 驱动', 'STM32/06-SPI驱动.html'),
        ('07 I2C 驱动', 'STM32/07-I2C驱动.html'),
        ('08 ADC 与 DMA', 'STM32/08-ADC与DMA.html'),
        ('09 定时器与 PWM', 'STM32/09-定时器与PWM.html'),
        ('10 看门狗', 'STM32/10-看门狗.html'),
    ]},
    {"id": "esp32", "title": "ESP32", "items": [
        ('01 入门与 STM32 对比', 'ESP32/01-入门与STM32对比.html'),
        ('02 WiFi STA 与 AP', 'ESP32/02-WiFi-STA与AP.html'),
        ('03 BLE GATT', 'ESP32/03-BLE-GATT.html'),
        ('04 Deep Sleep', 'ESP32/04-Deep-Sleep.html'),
        ('05 NVS 存储', 'ESP32/05-NVS存储.html'),
        ('06 HTTP 与 WebServer', 'ESP32/06-HTTP与WebServer.html'),
    ]},
    {"id": "adv", "title": "进阶", "items": [
        ('01 FreeRTOS 任务', '进阶/01-FreeRTOS任务.html'),
        ('02 同步机制', '进阶/02-同步机制.html'),
        ('03 低功耗设计', '进阶/03-低功耗设计.html'),
        ('04 OTA 固件升级', '进阶/04-OTA固件升级.html'),
        ('05 Bootloader', '进阶/05-Bootloader.html'),
        ('06 内存优化', '进阶/06-内存优化.html'),
        ('07 JTAG 与 SWD 调试', '进阶/07-JTAG与SWD调试.html'),
        ('08 代码规范', '进阶/08-代码规范.html'),
    ]},
    {"id": "ios", "title": "iOS 联动", "items": [
        ('01 BLE 基础', 'iOS联动/01-BLE基础.html'),
        ('02 CoreBluetooth 实战', 'iOS联动/02-CoreBluetooth实战.html'),
        ('03 WiFi 配网', 'iOS联动/03-WiFi配网.html'),
        ('04 MQTT App 端', 'iOS联动/04-MQTT-App端.html'),
        ('05 全栈架构', 'iOS联动/05-全栈架构.html'),
        ('06 后台蓝牙', 'iOS联动/06-后台蓝牙.html'),
    ]},
    {"id": "proj", "title": "项目实战", "items": [
        ('01 智能台灯', '项目实战/01-智能台灯.html'),
        ('02 远程开关', '项目实战/02-远程开关.html'),
        ('03 环境监测', '项目实战/03-环境监测.html'),
        ('04 蓝牙小车', '项目实战/04-蓝牙小车.html'),
        ('05 农业 IoT', '项目实战/05-农业IoT.html'),
        ('06 工业采集', '项目实战/06-工业采集.html'),
    ]},
    {"id": "scene", "title": "应用场景", "items": [
        ('01 行业应用全景', '应用场景/01-行业应用全景.html'),
        ('02 如何接单赚钱', '应用场景/02-如何接单赚钱.html'),
        ('03 职业规划', '应用场景/03-职业规划.html'),
    ]},
    {"id": "exercise", "title": "练习", "items": [
        ('01 入门采购清单', '练习/01-入门采购清单.html'),
        ('02 自测题（15 题）', '练习/02-自测题.html'),
        ('03 12 周学习计划', '练习/03-12周学习计划.html'),
    ]},
    {"id": "interview", "title": "面试题", "items": [
        ('01 嵌入式基础 50 题', '面试题/01-嵌入式基础50题.html'),
        ('02 进阶与 iOS 联动 30 题', '面试题/02-进阶与iOS联动30题.html'),
    ]},
]
